import cheesePizza from '../img/image/cheese_pizza.jpg';
import pepperoniPizza from '../img/image/pepperoni_pizza.jpg';
import chickenPizza from '../img/image/chicken_pizza.jpg';
import chiliPizza from '../img/image/chili_pizza.jpg';
import dodoPizza from '../img/image/dodo_pizza.jpg';
import grillPizza from '../img/image/grill_pizza.jpg';
import carbonaraPizza from '../img/image/carbonara_pizza.jpg';
import margaritaPizza from '../img/image/margarita_pizza.jpg';
import meatPizza from '../img/image/meat_pizza.jpg';
import pestoPizza from '../img/image/pesto_pizza.jpg';

export const pizzaCardMock = [
  {
    id: 0,
    imageUrl: pepperoniPizza,
    title: 'Пепперони Фреш с перцем',
    types: [0, 1],
    sizes: [26, 30, 40],
    price: 803,
    category: 0,
    rating: 4,
  },
  {
    id: 1,
    imageUrl: cheesePizza,
    title: 'Сырная',
    types: [0],
    sizes: [26, 40],
    price: 245,
    category: 0,
    rating: 6,
  },
  {
    id: 2,
    imageUrl: chickenPizza,
    title: 'Цыпленок барбекю',
    types: [0],
    sizes: [26, 40],
    price: 295,
    category: 1,
    rating: 4,
  },
  {
    id: 3,
    imageUrl: dodoPizza,
    title: 'Кисло-сладкий цыпленок',
    types: [1],
    sizes: [26, 30, 40],
    price: 275,
    category: 2,
    rating: 2,
  },
  {
    id: 4,
    imageUrl: carbonaraPizza,
    title: 'Чизбургер-пицца',
    types: [0, 1],
    sizes: [26, 30, 40],
    price: 415,
    category: 3,
    rating: 8,
  },
  {
    id: 5,
    imageUrl: grillPizza,
    title: 'Крэйзи пепперони',
    types: [0],
    sizes: [30, 40],
    price: 580,
    category: 2,
    rating: 2,
  },
  {
    id: 6,
    imageUrl: pepperoniPizza,
    title: 'Пепперони',
    types: [0, 1],
    sizes: [26, 30, 40],
    price: 675,
    category: 1,
    rating: 9,
  },
  {
    id: 7,
    imageUrl: margaritaPizza,
    title: 'Маргарита',
    types: [0, 1],
    sizes: [26, 30, 40],
    price: 450,
    category: 4,
    rating: 10,
  },
  {
    id: 8,
    imageUrl: meatPizza,
    title: 'Четыре сезона',
    types: [0, 1],
    sizes: [26, 30, 40],
    price: 395,
    category: 5,
    rating: 10,
  },
  {
    id: 9,
    imageUrl: pestoPizza,
    title: 'Овощи и грибы 🌱',
    types: [0, 1],
    sizes: [26, 30, 40],
    price: 285,
    category: 5,
    rating: 7,
  },
  {
    id: 10,
    imageUrl: grillPizza,
    title: 'Крэйзи пепперони',
    types: [0],
    sizes: [30, 40],
    price: 580,
    category: 2,
    rating: 2,
  },
  {
    id: 11,
    imageUrl: carbonaraPizza,
    title: 'Чизбургер-пицца',
    types: [0, 1],
    sizes: [26, 30, 40],
    price: 415,
    category: 3,
    rating: 8,
  },
];
